name: jpl_automated_testing_framework_plugin_logging
description: 'Library to use provide logging capabilities and evaluations to the testing framework.'
version: '4.0.1+14'
homepage: https://github.com/NicoRodsevich/jpl
repository: https://github.com/NicoRodsevich/jpl/tree/main/packages/jpl_automated_testing_framework_plugin_logging
issue_tracker: https://github.com/NicoRodsevich/jpl/issues

environment: 
  sdk: ^3.6.0
dependencies: 
  jpl_automated_testing_framework: "^5.0.1"
  flutter: 
    sdk: 'flutter'
  jpl_form_validation: "^3.2.0"
  jpl_json_class: "^3.0.1"
  jpl_json_theme: "^11.0.0"
  logging: '^1.1.1'
  jpl_static_translations: "^2.1.2"

dev_dependencies:
  flutter_test:
    sdk: 'flutter'


flutter: 
  uses-material-design: true

ignore_updates: 
  - 'archive'
  - 'async'
  - 'boolean_selector'
  - 'characters'
  - 'charcode'
  - 'collection'
  - 'clock'
  - 'crypto'
  - 'fake_async'
  - 'file'
  - 'matcher'
  - 'material_color_utilities'
  - 'meta'
  - 'path'
  - 'source_span'
  - 'stack_trace'
  - 'stream_channel'
  - 'string_scanner'
  - 'sync_http'
  - 'term_glyph'
  - 'test_api'
  - 'typed_data'
  - 'vector_math'
  - 'webdriver'
