name: jpl_json_dynamic_widget_annotations
description: 'Annotations for the json_dynamic_widget library.'
version: '1.0.0+11'
homepage: https://github.com/NicoRodsevich/jpl
repository: https://github.com/NicoRodsevich/jpl/tree/main/packages/jpl_json_dynamic_widget_annotations
issue_tracker: https://github.com/NicoRodsevich/jpl/issues

environment: 
  sdk: ^3.6.0
analyzer: 
  exclude: 
    - 'lib/generated/**'
    - 'lib/**/*.g.dart'

dev_dependencies: 
  flutter_lints: ^6.0.0
  test: '^1.25.2'

ignore_updates: 
  - 'archive'
  - 'async'
  - 'boolean_selector'
  - 'characters'
  - 'charcode'
  - 'collection'
  - 'clock'
  - 'crypto'
  - 'fake_async'
  - 'file'
  - 'matcher'
  - 'material_color_utilities'
  - 'meta'
  - 'path'
  - 'source_span'
  - 'stack_trace'
  - 'stream_channel'
  - 'string_scanner'
  - 'sync_http'
  - 'term_glyph'
  - 'test_api'
  - 'typed_data'
  - 'vector_math'
  - 'webdriver'
