name: jpl_automated_testing_framework_plugin_firebase_storage
publish_to: none
description: "Library to use Google's Firebase Storage as a mechanism for automated tests and test results."
version: '5.0.1+14'
homepage: https://github.com/NicoRodsevich/jpl
repository: https://github.com/NicoRodsevich/jpl/tree/main/packages/jpl_automated_testing_framework_plugin_firebase_storage
issue_tracker: https://github.com/NicoRodsevich/jpl/issues

environment: 
  sdk: ^3.6.0
dependencies: 
  jpl_automated_testing_framework: "^5.0.1"
  convert: '^3.1.1'
  firebase_auth: '^4.4.2'
  firebase_core: '^2.10.0'
  firebase_storage: '^11.1.1'
  flutter: 
    sdk: 'flutter'
  jpl_form_validation: "^3.2.0"
  jpl_json_class: "^3.0.1"
  logging: '^1.1.1'
  jpl_static_translations: "^2.1.2"

dev_dependencies: 
  flutter_test: 
    sdk: 'flutter'


flutter: 
  uses-material-design: true

ignore_updates: 
  - 'archive'
  - 'async'
  - 'boolean_selector'
  - 'characters'
  - 'charcode'
  - 'collection'
  - 'clock'
  - 'crypto'
  - 'fake_async'
  - 'file'
  - 'matcher'
  - 'material_color_utilities'
  - 'meta'
  - 'path'
  - 'source_span'
  - 'stack_trace'
  - 'stream_channel'
  - 'string_scanner'
  - 'sync_http'
  - 'term_glyph'
  - 'test_api'
  - 'typed_data'
  - 'vector_math'
  - 'webdriver'
