name: jpl_json_conditional
description: 'A library to create conditional evaluators from JSON or JSON-like structures.'
version: '3.0.1+17'
homepage: https://github.com/NicoRodsevich/jpl
repository: https://github.com/NicoRodsevich/jpl/tree/main/packages/jpl_json_conditional
issue_tracker: https://github.com/NicoRodsevich/jpl/issues

environment:
  sdk: ^3.6.0
analyzer:
  exclude:
    - 'lib/generated/**'

dependencies:
  jpl_json_class: "^3.0.1"
  meta: '^1.12.0'

dev_dependencies:
  flutter_lints: ^6.0.0
  test: '^1.25.8'

permittedLicenses:
  - 'Apache-2.0'
  - 'BSD-2-Clause'
  - 'BSD-3-Clause'
  - 'MIT'
  - 'MIT-Modern-Variant'
  - 'MPL-2.0'
  - 'Zlib'

packageLicenseOverride:
  flutter: 'BSD-3-Clause'
  flutter_driver: 'BSD-3-Clause'
  flutter_goldens: 'BSD-3-Clause'
  flutter_localizations: 'BSD-3-Clause'
  flutter_web_plugins: 'BSD-3-Clause'
  flutter_test: 'BSD-3-Clause'
  fuchsia_remote_debug_protocol: 'BSD-3-Clause'
  integration_test: 'BSD-3-Clause'
  rxdart: 'Apache-2.0'

ignore_updates:
  - 'archive'
  - 'async'
  - 'boolean_selector'
  - 'characters'
  - 'charcode'
  - 'collection'
  - 'clock'
  - 'crypto'
  - 'fake_async'
  - 'file'
  - 'matcher'
  - 'material_color_utilities'
  - 'meta'
  - 'path'
  - 'source_span'
  - 'stack_trace'
  - 'stream_channel'
  - 'string_scanner'
  - 'sync_http'
  - 'term_glyph'
  - 'test_api'
  - 'typed_data'
  - 'vector_math'
  - 'webdriver'
